WATCHLIST = [
    "GC=F",
    "BTC-USD",
    "EURUSD=X",
    "USDJPY=X",
    "AUDUSD=X",
    "EURJPY=X",
]

SYMBOL_NAMES = {
    "GC=F": "XAUUSD",
    "BTC-USD": "BTCUSD",
    "EURUSD=X": "EURUSD",
    "USDJPY=X": "USDJPY",
    "AUDUSD=X": "AUDUSD",
    "EURJPY=X": "EURJPY",
}

TIMEFRAME_MACRO = "1d"
TIMEFRAME_TREND = "1h"
TIMEFRAME_ENTRY = "5m"

HISTORY = 500
